<a href="https://colab.research.google.com/github/lucianosilva-github/visaocomputacional/blob/master/Aula%2021/Visa%CC%83o_Computacional_Aula_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **VISÃO COMPUTACIONAL - AULA 21**

**Objetivos da aula:**

*   apresentar o conceito de busca por padrões 3D em nuvens de pontos
*   apresentar os algoritmos PTP e PTPL para registro ICP
*   implementar e praticar com os algoritmos PTP e PTPL


## **BUSCA POR PADRÕES 3D EM NUVENS DE PONTOS**

A busca semântica em nuvens de pontos é um recurso moderno em Visão Computacional 3D e permite que padrões 3D (também definidos como nuvens de pontos) sejam procurados em outras nuvens de pontos. Abaixo temos um exemplo de padrão (amarelo) sendo procurado em uma nuvem de pontos (azul).

<img src="https://lh3.googleusercontent.com/proxy/QtWMtYLRDuk9Zzg_J6KyIxcobTZvpsIcIfvUsFbW3WT0q_ikcTGdZbhuanaWbSJJcxKxC5-8swPN-tLpQerAFu0Awdw04c2EDpuDL5xkBg73F_gw-czDue-4SfLxaakXnQWiLj95waYqZA"> 
</img>

Este procedimento é chamado registro ICP (Iterative Closest Point). Existem diversos algoritmos de registro ICP. Um estudo comparativo bastante completo destes algoritmos pode ser encontrado no artigo abaixo:

S. Rusinkiewicz and M. Levoy. **Efficient variants of the ICP algorithm**. In 3-D Digital Imaging and Modeling, 2001.

O módulo Open3D possui um suporte bastante efetivo para ICP. Trabalharemos com dois algoritmos de ICP implementandos na Open3D: ICP Ponto-a-Ponto e o ICP Ponto-a-Plano. Para usar estes dois algoritmos, vamos utilizar dois arquivos de nuvens de pontos: um para o espaço de busca e outro para o padrão a ser encontrado.

In [ ]:
!pip install open3d

Abertura e exibição do espaço de busca.

In [2]:
import open3d as o3d
import numpy as np

pcdb = o3d.io.read_point_cloud("espaco_busca.pcd")
print(pcdb)
points=np.asarray(pcdb.points)
print(points)


PointCloud with 198835 points.
[[1.01953125 0.88671875 2.27726722]
 [1.04296875 0.88671875 2.27699804]
 [1.05859375 0.88671875 2.27722216]
 ...
 [1.26609075 2.37890625 2.26171875]
 [1.26171875 2.38015151 2.26171875]
 [1.26171875 2.37890625 2.26367211]]


In [ ]:
import plotly.graph_objects as go

fig = go.Figure(
    data=[
        go.Scatter3d(
            x=points[:,0], y=points[:,1], z=points[:,2], 
            mode='markers',
            marker=dict(size=1, color=np.asarray(pcdb.colors))
        )
    ],
    layout=dict(
        scene=dict(
            xaxis=dict(visible=False),
            yaxis=dict(visible=False),
            zaxis=dict(visible=False)
        )
    )
)
fig.show()

Abertura e exibição do padrão a ser encontrado:

In [5]:
pcdp = o3d.io.read_point_cloud("padrao.pcd")
print(pcdb)
points=np.asarray(pcdp.points)
print(points)

PointCloud with 198835 points.
[[1.32421875 1.16796875 1.39391088]
 [1.10546875 1.18451285 1.33203125]
 [1.10546875 1.18359375 1.33258736]
 ...
 [2.76086402 2.58203125 1.14453125]
 [2.75390625 2.58381176 1.14453125]
 [2.75390625 2.58203125 1.15058577]]


In [ ]:
fig = go.Figure(
    data=[
        go.Scatter3d(
            x=points[:,0], y=points[:,1], z=points[:,2], 
            mode='markers',
            marker=dict(size=1, color=np.asarray(pcdp.colors))
        )
    ],
    layout=dict(
        scene=dict(
            xaxis=dict(visible=False),
            yaxis=dict(visible=False),
            zaxis=dict(visible=False)
        )
    )
)
fig.show()

In [ ]:
Propositalmente, o padrão ser busca neste exemplo é um recorte do espaço de busca. No caso geral, as duas nuvens de pontos podem ser quaisquer.

## **ALGORITMO PTP (POINT-TO-POINT)**

O Algoritmo de Registro PTP (Point-To-Point) depende de dois parâmetros além do espaço de busca: uma matriz de transformação inicial e um limiar (threshold): 

In [12]:
trans_init = np.asarray([[0.862, 0.011, -0.507, 0.5],
                         [-0.139, 0.967, -0.215, 0.7],
                         [0.487, 0.255, 0.835, -1.4], 
                         [0.0, 0.0, 0.0, 1.0]])
threshold=0.02
result = o3d.pipelines.registration.registration_icp(
    pcdb, pcdp, threshold, trans_init,
    o3d.pipelines.registration.TransformationEstimationPointToPoint(),
    o3d.pipelines.registration.ICPConvergenceCriteria(max_iteration=2000))
print(result)
print("Transformation Matrix:")
print(result.transformation)

RegistrationResult with fitness=6.211230e-01, inlier_rmse=6.583448e-03, and correspondence_set size of 123501
Access transformation to get result.
Transformation Matrix:
[[ 0.84024592  0.00687676 -0.54241281  0.6463702 ]
 [-0.14819104  0.96517833 -0.21706206  0.81180074]
 [ 0.52111439  0.26195134  0.81189372 -1.48346821]
 [ 0.          0.          0.          1.        ]]


## **EXERCÍCIO**

O Algoritmo PTP implementado na Open3D é devido a Bels & McKay (1992). Este algoritmo é apresentado no artigo abaixo:

http://graphics.stanford.edu/courses/cs164-09-spring/Handouts/paper_icp.pdf

Leia o artigo acima e explique como este algoritmo funciona.

digite sua resposta aqui

## **EXERCÍCIO**

Qual é a influência do parâmetro threshold no algoritmo PTP ? Faça experimentos na célula abaixo para embasar sua resposta.

In [ ]:
#digite sua resposta aqui

## **EXERCÍCIO**

Qual é a influência do parâmetro relativo à matriz de transformação inicial no algoritmo PTP ? Faça experimentos na célula abaixo para embasar sua resposta.

In [ ]:
#digite sua resposta aqui

## **ALGORITMO PTPL (POINT-TO-PLANE)**

O Algoritmo de Registro PTPL (Point-To-Plane) também depende de dois parâmetros além do espaço de busca: uma matriz de transformação inicial e um limiar (threshold):

In [ ]:
trans_init = np.asarray([[0.862, 0.011, -0.507, 0.5],
                         [-0.139, 0.967, -0.215, 0.7],
                         [0.487, 0.255, 0.835, -1.4], 
                         [0.0, 0.0, 0.0, 1.0]])
threshold=0.02
result = o3d.pipelines.registration.registration_icp(
    pcdb, pcdp, threshold, trans_init,
    o3d.pipelines.registration.TransformationEstimationPointToPlane(),
    o3d.pipelines.registration.ICPConvergenceCriteria(max_iteration=2000))
print(result)
print("Transformation Matrix:")
print(result.transformation)

## **EXERCÍCIO**

O Algoritmo PTPL implementado na Open3D é devido a Low (2004). Este algoritmo é apresentado no artigo abaixo:

https://www.comp.nus.edu.sg/~lowkl/publications/lowk_point-to-plane_icp_techrep.pdf

Leia o artigo acima e explique como este algoritmo funciona.

Digite sua resposta aqui

##**EXERCÍCIO**
Qual é a diferença entre os algoritmos PTP e PTPL ?

Digite sua resposta aqui...

## **EXERCÍCIO**

Qual é a influência do parâmetro threshold no algoritmo PTPL ? Faça experimentos na célula abaixo para embasar sua resposta.

In [ ]:
#digite sua análise aqui

## **EXERCÍCIO**

Qual é a influência do parâmetro relativo à matriz de transformação inicial no algoritmo PTPL ? Faça experimentos na célula abaixo para embasar sua resposta.

In [ ]:
#digite sua análise aqui